#This is an ingress yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.environment.name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /nof
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.environment.name }}-service
                port:
                  number: {{ .Values.service.port }}

